project:
  type: website
  output-dir: docs

website:
  title: "Ecologia de Paisagens com R"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Apresentação"
        contents:
          - index.qmd
          - preface.qmd
          - intro.qmd
      - section: escala-met.qmd
        contents:
          - escala.qmd
          - metricas.qmd
      - section: codigo-R.qmd
        contents:
          - codigo-livro.qmd
          - codigo-raster.qmd
          - codigo-vector.qmd
      - section: "Bibliografia"
        contents:
          - references.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
    cover-image: cover.png

bibliography: references.bib

lang: pt-BR
language:
  label:
    fig: "Figura "
    tab: "Tabela "
  ui:
    chapter_name: "Capítulo "