project:
  type: website
  output-dir: docs

website:
  title: "Ecologia de Paisagens com R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - preface.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

    contents:
    - intro.qmd
    - section: escala-met.qmd
      contents:
      - escala.qmd
      - metricas.qmd
    - section: codigo-R.qmd
      contents:
        - codigo-livro.qmd
        - codigo-raster.qmd
        - codigo-vector.qmd
    - references.qmd
    cover-image: cover.png

bibliography: references.bib

lang: pt-BR
language:
  label:
    fig: "Figura "
    tab: "Tabela "
  ui:
    chapter_name: "Capítulo "